version: '3.8'

services:
    alpine:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_docker
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./backend/conf/site.conf:/etc/nginx/http.d/default.conf
            - ./backend/src:/var/www/html
        networks:
            - acpSymfony

    db:
        image: mariadb:10.8.2
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'ChangeMeLater'
        networks:
            - acpSymfony

    maildev:
        image: maildev/maildev
        container_name: maildev_docker
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - acpSymfony

    caddy:
        image: dunglas/mercure
        restart: unless-stopped
        container_name: mercure_docker
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            MERCURE_EXTRA_DIRECTIVES:
                cors_origins "http://localhost:3000"
                cors_origins "http://localhost:8245"
#                anonymous
        # Uncomment the following line to enable the development mode
#        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "9090:80"
            - "443:443"
#        volumes:
#            - caddy_data:/data
#            - caddy_config:/config
        networks:
            - acpSymfony
volumes:
    db-data:

networks:
    acpSymfony:
